// Package plumbing for clicker/cmd/clicker (sans main.go, which is src/main.rs).
// Declares one module per ported command file; ordering follows main.go's
// AddCommand registration list. Platform-specific files are #[cfg]-gated.

mod a11y_tree;
mod attr;
mod back;
mod check_cmd;
mod click;
mod completion;
mod content;
mod cookies;
mod count;
mod daemon_client;
mod daemon_cmd;
#[cfg(unix)]
mod daemon_unix;
#[cfg(windows)]
mod daemon_windows;
mod dblclick;
mod diagnostics;
pub use diagnostics::*;
pub use a11y_tree::{a11y_tree_command, run_a11y_tree};
pub use attr::{attr_command, run_attr};
pub use back::{back_command, run_back};
pub use check_cmd::{check_command, run_check};
pub use click::{click_command, run_click};
pub use completion::{completion_command, run_completion};
pub use count::{count_command, run_count};
pub use daemon_cmd::{daemon_command, run_daemon};
pub use dblclick::{dblclick_command, run_dblclick};
pub use content::{content_command, run_content};
pub use cookies::{cookies_command, run_cookies};
pub use dialog::{dialog_command, run_dialog};
pub use download::{download_command, run_download};
pub use frame::{frame_command, run_frame};
pub use frames::{frames_command, run_frames};
pub use upload::{run_upload, upload_command};
pub use skill::{run_skill, skill_command};
pub use help::{command_help, intercept_help, root_help, shows_help_on_no_subcommand};
pub use map::{map_command, run_map};
pub use mcp_cmd::{mcp_command, run_mcp};
pub use diff::{diff_command, run_diff};
pub use geolocation::{geolocation_command, run_geolocation};
pub use media::{media_command, run_media};
pub use viewport::{run_viewport, viewport_command};
pub use window::{run_window, window_command};
pub use drag::{drag_command, run_drag};
pub use eval::{eval_command, run_eval};
pub use fill::{fill_command, run_fill};
pub use find::{find_command, run_find};
pub use focus::{focus_command, run_focus};
pub use forward::{forward_command, run_forward};
pub use highlight::{highlight_command, run_highlight};
pub use hover::{hover_command, run_hover};
pub use html::{html_command, run_html};
pub use is::{is_command, run_is};
pub use keys::{keys_command, run_keys};
pub use mouse::{mouse_command, run_mouse};
pub use navigate::{navigate_command, run_navigate};
pub use page::{page_command, run_page};
pub use pages::{pages_command, run_pages};
pub use pdf::{pdf_command, run_pdf};
pub use pipe::{pipe_command, run_pipe};
pub use record::{record_command, run_record};
pub use press::{press_command, run_press};
pub use reload::{reload_command, run_reload};
pub use screenshot::{run_screenshot, screenshot_command};
pub use scroll::{run_scroll, scroll_command};
pub use select_cmd::{run_select, select_command};
pub use serve::{run_serve, serve_command};
pub use sleep_cmd::{run_sleep, sleep_command};
pub use start::{run_start, start_command};
pub use stop::{run_stop, stop_command};
pub use storage::{run_storage, storage_command};
pub use text::{run_text, text_command};
pub use title::{run_title, title_command};
pub use type_cmd::{run_type, type_command};
pub use uncheck::{run_uncheck, uncheck_command};
pub use url_cmd::{run_url, url_command};
pub use value::{run_value, value_command};
pub use wait_cmd::{run_wait, wait_command};
#[cfg(unix)]
mod dial_unix;
#[cfg(windows)]
mod dial_windows;
mod dialog;
mod diff;
mod download;
mod drag;
mod eval;
mod fill;
mod find;
mod focus;
mod forward;
mod frame;
mod frames;
mod geolocation;
mod help;
mod help_text;
mod helpers;
mod highlight;
mod hover;
mod html;
mod is;
mod keys;
mod map;
mod mcp_cmd;
mod media;
mod mouse;
mod navigate;
mod output;
mod page;
mod pages;
mod pdf;
mod pipe;
#[cfg(unix)]
mod pipe_unix;
#[cfg(windows)]
mod pipe_windows;
mod press;
mod record;
mod reload;
mod screenshot;
mod scroll;
mod select_cmd;
mod serve;
mod skill;
mod sleep_cmd;
mod start;
mod stop;
mod storage;
mod text;
mod title;
mod type_cmd;
mod uncheck;
mod upload;
mod url_cmd;
mod value;
mod viewport;
mod wait_cmd;
mod window;
